### ISSUE TITLE
Can't run the example

### ISSUE THREAD

**Issue by hasansezertasan** [alex-oleshkevich/ohmyadmin#6]
Hello 👋 Great looking project. Keep up the good work 🚀 

I have cloned the repo and ran these commands:

```console
poetry install --all-extras
uvicorn examples.app:app
```

When I navigate to `http://localhost:8000/admin`, the application redirects me to `http://localhost:8000/admin/login?next=/admin/` and I  see an empty page.

Here is the uvicorn log:

```python
$ uvicorn examples.app:app
INFO:     Started server process [37828]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:50139 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:50139 - "GET / HTTP/1.1" 302 Found
INFO:     127.0.0.1:50139 - "GET /login?next=/admin/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:50139 - "GET /main.css?1706190422.890375 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50139 - "GET /main.js?1706190422.890375 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50148 - "GET /main.js?1706190422.890375 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50139 - "GET /logo_square.svg?1706190422.890375 HTTP/1.1" 404 Not Found
```

I couldn't find any of those static files and I don't know where to get them. Can you add an instruction/guideline that explains how to run the example?

**Comment by alex-oleshkevich** [comment]
assets are in the `assets` directory. 
```shell
cd assets
yarn install
yarn build
```

if you just want to play around then better to install via pip. the package there contains prebuilt assets

**Comment by alex-oleshkevich** [comment]
if you want to contribute, please check out `ng` branch (https://github.com/alex-oleshkevich/ohmyadmin/tree/ng)
